[package]
name = "debug_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9"
bevy_framepace = "0.11"
egui = "0.20.0"
bevy_egui = "0.19"
bevy-inspector-egui = "0.17.0"
egui_dock = "0.3"